- name: Gathering Arista facts
  eos_facts:
  
- name: Send Report to Mattermost
  mattermost:
    api_key: "{{ mattermost_token }}"
    url: "{{ mattermost_url }}"
    text: "{{ lookup('template','mattermost_eos.j2') }}"
    channel: "{{ mattermost_channel }}"
    validate_certs: no
  run_once: true
