- name: Gathering Arista facts
  ios_facts:
  register: all_facts
  
- name: Create HTML Report
  template:
    src: report-eos.j2
    dest: "{{ file_path }}"
  delegate_to: localhost
  run_once: true