---
- name: "Include Inventory Report Tasks"
  include_tasks: "{{ ansible_network_os }}.yml"
  with_first_found:
    - files:
        - "tasks/{{ ansible_network_os }}.yml"
      skip: true

- name: Include Confluence Tasks
  include_tasks: confluence.yml
